AdvertApi.Management.Web/Controllers/AccountsController.cs
using System.Threading.Tasks;
using AdvertApi.Management.Web.Models.Accounts;
using Amazon.AspNetCore.Identity.Cognito;
using Amazon.Extensions.CognitoAuthentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdvertApi.Management.Web.Controllers
{
    public class AccountsController : Controller
    {
        private readonly SignInManager<CognitoUser> _signInManager;
        private readonly UserManager<CognitoUser> _userManager;
        private readonly CognitoUserPool _pool;

        public AccountsController(SignInManager<CognitoUser> signInManager, UserManager<CognitoUser> userManager, CognitoUserPool pool)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _pool = pool;
        }
       

        [HttpGet]
        public async Task<IActionResult> SignUp()
        {
            var model = new SignUpModel();
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Confirm(ConfirmModel model)
        {
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Login(LoginModel model)
        {
            return View(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> Signup(SignUpModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _pool.GetUser(model.Email);
                
                // we have name attribute required. At the moment, we dont have a name passed in, so we can use the email temporarily.
                // user will not be null even if it does not exist.
                user.Attributes.Add("name",model.Email);
                // without second parameter, a new user is created with password autogenerated. 
                // if is user exists, it will fail here.
                var createResult = await _userManager.CreateAsync(user, model.Password);

                if (createResult.Succeeded)
                {
                    var confirmModel = new ConfirmModel
                    {
                        Email = model.Email,
                        Code = string.Empty
                    };
                    
                    RedirectToAction("Confirm", confirmModel);
                }
                
                foreach (var item in createResult.Errors) 
                    ModelState.AddModelError(item.Code, item.Description);
            }

            return View(model);
        }
        
        [HttpPost]
        [ActionName("Confirm")]
        public async Task<IActionResult> ConfirmPost(ConfirmModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                if (user == null)
                {
                    ModelState.AddModelError("NotFound", "A user with given email address was not found.");
                    return View(model);
                }

              //  var result = await _userManager.ConfirmEmailAsync(user, model.Code);
                var result = await ((CognitoUserManager<CognitoUser>) _userManager).ConfirmSignUpAsync(user, model.Code, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                foreach (var item in result.Errors) ModelState.AddModelError(item.Code, item.Description);
                return View(model);
            }

            return View(model);
        }

        [HttpPost]
        [ActionName("Login")]
        public async Task<IActionResult> LoginPost(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email,
                    model.Password, model.RememberMe, false);
                if (result.Succeeded)
                    return RedirectToAction("Index", "Home");
                ModelState.AddModelError("LoginError", "Email and password do not match");
            }

            return View("Login", model);
        }
        
        public async Task<IActionResult> Signout()
        {
            if (User.Identity.IsAuthenticated) await _signInManager.SignOutAsync().ConfigureAwait(false);
            return RedirectToAction("Login");
        }
    }
}

AdvertApi.Management.Web/Controllers/AdvertsUploadController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using AdvertApi.Management.Web.Models;
using AdvertApi.Management.Web.ServiceClients;
using AdvertApi.Management.Web.Services;
using AdvertApi.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AdvertApi.Management.Web.Controllers
{
    public class AdvertsUploadController : Controller
    {
        private readonly IFileUploader _fileUploader;
        private readonly IAdvertApiClient _advertApiClient;
        private readonly IMapper _mapper;

        public AdvertsUploadController(IFileUploader fileUploader, IAdvertApiClient advertApiClient, IMapper mapper)
        {
            _fileUploader = fileUploader;
            _advertApiClient = advertApiClient;
            _mapper = mapper;
        }
      
        [Authorize]
        public IActionResult Create(CreateAdvertViewModel model)
        {
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAdvertViewModel model, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                
                var createAdvertModel = _mapper.Map<CreateAdvertModel>(model);
                var response = await _advertApiClient.CreateAsync(createAdvertModel);
                var id = response.Id;
                
                var fileName = "";
                if (imageFile != null)
                {
                    fileName = !string.IsNullOrEmpty(imageFile.FileName) ? Path.GetFileName(imageFile.FileName) : id;
                    var filePath = $"{id}/{fileName}";

                    try
                    {
                        using (var readStream = imageFile.OpenReadStream())
                        {
                            var result = await _fileUploader.UploadFileAsync(filePath, readStream);
                            if (!result)
                                throw new Exception(
                                    " Could not upload image to the file repository. Please see logs for more detail");
                        }

                        var confirmModel = new ConfirmAdvertRequest
                        {
                            Id = id,
                            FilePath = filePath,
                            Status = AdvertStatus.Active
                        };
                        var canConfirm = await _advertApiClient.ConfirmAsync(confirmModel);
                        if (!canConfirm)
                        {
                            throw new Exception($"Cannot confirm upload for advert {id}");
                        }
                        return RedirectToAction("Index", "Home");
                    }
                    catch (Exception ex)
                    {
                        var confirmModel = new ConfirmAdvertRequest
                        {
                            Id = id,
                            FilePath = filePath,
                            Status = AdvertStatus.Pending
                        };
                        await _advertApiClient.ConfirmAsync(confirmModel);
                        Console.WriteLine(ex.Message);
                    }
                }
            }

            return View(model);
        }
    }
}

AdvertApi.Management.Web/Views/Shared/AdvertDetail.cshtml
<div class="modal" tabindex="-1" role="dialog" id="detailsModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Advertisement Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="border-dark rounded advertDetailBox" id="advertDetailBox">
                    <div style="text-align:center;" >
                        <img id="detailImage" class="box-shadow"/>
                    </div>
                    <h4 id="detailTitle"></h4>
                    <p id="detailDesc"></p>
                    <p id="detailPrice"></p>
                </div>
            </div>
        </div>
    </div>
</div>

AdvertApi.Management.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Advert Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                               <img src="https://image.flaticon.com/icons/png/128/1335/1335806.png" class="w-32" /> Web Advertisements
                           </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @if (User.Identity.IsAuthenticated)
                            {
            
                                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                    <ul class="navbar-nav flex-grow-1">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark nav-button-border" asp-area="" asp-controller="Home" asp-action="Index">
                                                Brows Ads
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark nav-button-border" asp-area="" asp-controller="AdvertsUpload" asp-action="Create">
                                                Create Ads
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="p-2 border-info" style="font-family: 'Actor', sans-serif;">
                                    Hello @User.Identity.Name
                                </div>
                                <div class="p-2 border-info ml-1">
                                    <a asp-controller="Accounts" asp-action="Signout">Sign Out</a>
                                </div>
                            }
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - AdvertApi.Management.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>